### ISSUE TITLE
Hash Support

### ISSUE THREAD

**Issue by gsquire** [jedisct1/rust-jumphash#4]
Would it make sense to add a Hasher trait bound to allow use of other hash functions? In my case I have smaller keys so I wanted to use the FNV function.

Thanks!

**Comment by jedisct1** [comment]
Is there a way to do that without breaking the current API?

**Comment by jedisct1** [comment]
I guess not :(

So, the change above adds a `CustomJumpHasher` structure that can handle custom hash functions.

Thanks for suggesting that change!

**Comment by gsquire** [comment]
Wow, thanks for the quick add! I agree that it would have been a breaking change for the original type.

Thanks again, this is great!
